CUDA_VISIBLE_DEVICES=0 python main_cannyedit.py \
--image_path './examples/bager1.png' \
--image_whratio_unchange \
--save_folder './results/bager_add_manwoman' \
--prompt_local "a man customer reading menu." \
--prompt_local "a woman waiter ready to serve." \
--mask_input "./examples/bager1_mask1.png"  \
--mask_input "./examples/bager1_mask2.png" \
--prompt_source 'A cozy restaurant entrance.' \
--prompt_target 'A cozy restaurant entrance with a man reads the menu while a woman waiter stands ready to serve.' \
--seed 6521909 \
--refine_mask --auto_mask_refine
